# Generated by Django 4.2.23 on 2025-08-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_school_and_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('active', '在读'), ('paused', '停课'), ('finished', '结课'), ('refunded', '退费清'), ('inactive', '潜在')], default='inactive', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '预初'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')]),
        ),
    ]
