# Generated by Django 4.2.23 on 2025-08-21 05:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_school_id_alter_student_academic_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_mode', models.CharField(choices=[('one_to_one', '一对一'), ('one_to_two', '一对二'), ('small_class', '小班')], default='small_class', max_length=20)),
                ('min_qty_sessions', models.PositiveIntegerField()),
                ('gift_sessions', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'edu_gift_rule',
                'ordering': ['-min_qty_sessions'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[], db_index=True)),
                ('course_mode', models.CharField(choices=[('one_to_one', '一对一'), ('one_to_two', '一对二'), ('small_class', '小班')], db_index=True, max_length=20)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'edu_price_rule',
                'ordering': ['grade', 'course_mode', '-min_qty'],
                'indexes': [models.Index(fields=['grade', 'course_mode', 'is_active'], name='edu_price_r_grade_060616_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_mode', models.CharField(choices=[('one_to_one', '一对一'), ('one_to_two', '一对二'), ('small_class', '小班')], db_index=True, max_length=20)),
                ('unit', models.CharField(max_length=16)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gift_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('direct_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade_snapshot', models.PositiveSmallIntegerField(choices=[])),
                ('price_rule_id', models.IntegerField(blank=True, null=True)),
                ('gift_rule_id', models.IntegerField(blank=True, null=True)),
                ('gift_source', models.CharField(default='auto', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True)),
                ('need_invoice', models.BooleanField(default=False)),
                ('invoice_title', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='students.student')),
            ],
            options={
                'db_table': 'edu_purchase_order',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='edu_purchas_student_b78f7b_idx')],
            },
        ),
    ]
