# Generated by Django 4.2.23 on 2025-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '预初'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')], db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grade_snapshot',
            field=models.PositiveSmallIntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '预初'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')]),
        ),
    ]
