# Generated by Django 4.2.23 on 2025-09-20 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_campus_cycle_lessonparticipant_cycleroster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePreplanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preplan_slots', to='schedule.classgroup')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preplan_slots', to='schedule.cycle')),
                ('room_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule.room')),
                ('teacher_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edu_cycle_preplan_slot',
                'ordering': ['cycle_id', 'weekday', 'start_time', 'id'],
                'indexes': [models.Index(fields=['cycle', 'weekday'], name='edu_cycle_p_cycle_i_b82d1e_idx'), models.Index(fields=['class_group'], name='edu_cycle_p_class_g_3d8b53_idx')],
                'unique_together': {('cycle', 'class_group', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
