# Generated by Django 4.2.23 on 2025-08-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduct_unit', models.CharField(choices=[('hours', '小时'), ('sessions', '节数')], max_length=16)),
                ('purchased_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('remaining_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('purchased_sessions', models.PositiveIntegerField(default=0)),
                ('remaining_sessions', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '在读'), ('paused', '停课'), ('finished', '结课'), ('refunded', '已退费'), ('closed', '关闭')], default='active', max_length=16)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'db_table': 'edu_enrollment',
                'indexes': [models.Index(fields=['student', 'status'], name='edu_enrollm_student_5e475f_idx')],
            },
        ),
    ]
