# Generated by Django 4.2.23 on 2025-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_mode',
            field=models.CharField(choices=[('one_to_one', '一对一'), ('one_to_two', '一对二'), ('small_class', '小班')], db_index=True, default='one_to_one', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='remaining_hours_gift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='remaining_sessions_gift',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'course_mode', 'status'), name='uniq_student_mode_active'),
        ),
    ]
